# Generated by Django 3.1.7 on 2024-03-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyAdminProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('academy_image', models.ImageField(upload_to='academy_images/')),
                ('academy_name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=50)),
                ('academy_address', models.CharField(max_length=100)),
                ('academy_phone', models.CharField(max_length=20)),
                ('total_capacity', models.IntegerField()),
                ('has_dormitory', models.BooleanField(default=False)),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_instructors', models.IntegerField()),
                ('events', models.TextField(blank=True, null=True)),
                ('class_capacity', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='AdultProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('is_parent', models.BooleanField(default=False)),
                ('looking_for_academy', models.CharField(blank=True, max_length=100, null=True)),
                ('school_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('experience', models.TextField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('grade', models.CharField(choices=[('elementary', '초등학생'), ('middle', '중학생'), ('high', '고등학생')], max_length=10)),
                ('academy', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('grade', models.CharField(choices=[('elementary', '초등학생'), ('middle', '중학생'), ('high', '고등학생')], max_length=10)),
                ('academy', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.adultprofile')),
            ],
        ),
    ]
