# Generated by Django 3.1.7 on 2024-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='course_category'),
        ),
        migrations.AlterField(
            model_name='hackwon',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hackwon',
            name='region',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hackwon',
            name='tuition',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
