# Generated by Django 3.1.7 on 2024-03-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20240307_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackwon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackwons', to='content.category'),
        ),
    ]
