# Generated by Django 3.1.7 on 2024-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20240307_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackwon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackwon',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
