# Generated by Django 3.1.7 on 2024-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20240307_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackwon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackwon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackwon',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
