# Generated by Django 3.1.7 on 2024-03-08 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_auto_20240307_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackwon',
            name='voter',
            field=models.ManyToManyField(related_name='voted_hackwons', to=settings.AUTH_USER_MODEL),
        ),
    ]
